import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navigation";
import Header from "./header";
import SessionProviderWrapper from "./SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-orange-100 flex min-h-screen flex-row min-w-96">
          <SessionProviderWrapper>
            <Navbar/>
            <div className="w-full min-h-screen flex flex-col">
                <Header/>
                {children}
            </div>
          </SessionProviderWrapper>
        </main>
      </body>
    </html>
  );
}
